[project]
name = "bofasa"
authors = [{name="Rauf Salamzade", email="salamzader@gmail.com"}]
version = "1.2.0"
description = "Bacterial multi-species orthology inference and analysis."
dependencies = [
    "biopython>=1.79",
    "scipy>=1.7.0",
    "pandas>=1.3.0",
    "tqdm>=4.62.0",
    "rich-argparse>=1.0.0",
    "plotly>=5.0.0",
    "xlsxwriter>=3.0.0",
    "pyhmmer>=0.10.0",
    "ete3>=3.1.0",
    "pyrodigal>=2.0.0",
]

[project.scripts]
bofasa = "bofasa.main:main"
extract_og_pairs = "bofasa.scripts.extract_og_pairs:extract_og_pairs"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
script-files=["src/bofasa/scripts/extract_og_pairs.py",
              "src/bofasa/scripts/extract_scc_og_pairs.py",
              "src/bofasa/scripts/print_og_itol_matrix.py",
              "src/bofasa/scripts/extract_genomad_proteomes.py",
              "src/bofasa/scripts/compare_og_pairs.py",
              "src/bofasa/scripts/determine_og_freqs.py",
              "src/bofasa/scripts/list_og_matrix.py"]

[tool.setuptools.packages.find]
where = ["src"]
