[project]
name = "bofasa"
authors = [{name="Rauf Salamzade", email="salamzader@gmail.com"}]
version = "1.0.0"
description = "Programs for bacterial multi-species orthology inference and analysis."

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
script-files=["bin/bofasa", "bin/prepare_input", "scripts/listAllGenomesInDirectory.py", "scripts/processNCBIGenBankAndCreateInputs.py", "scripts/runProdigalAndMakeInputsForBofasa.py"]

[tool.setuptools.packages.find]
where = ["src"]
