#!/workspace/local/rauf/bofasa/conda_env/bin/python3.11

### Program: determine_og_freqs
### Author: Rauf Salamzade, Aamuktha Kottapalli, Lindsay R. Kalan	
### Affiliation: University of Wisconsin - Madison, McMaster University

# BSD 3-Clause License
#
# Copyright (c) 2024, Rauf Salamzade
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import os
import sys
import argparse
from collections import defaultdict
from bofasa import util
from rich_argparse import RawTextRichHelpFormatter
import statistics

def create_parser():
	""" Parse arguments """
	parser = argparse.ArgumentParser(description="""
	Program: extract_og_pairs
	Authors: Rauf Salamzade, Aamuktha Kottapalli, Lindsay R. Kalan 
	Affiliation: University of Wisconsin - Madsion, McMaster University								  
								  
    extract_og_pairs: a simple script to list pairs of proteins in the 
    same ortholog group for method comparison. Takes in the results 
    folder for the program and outputs.

    Options for software supported include:
    ===================================================================
    - bofasa 
    - sonicparanoid
    - panaroo
    - scarap
	- pirate
    - orthofinder_hog (OrthoFinder v2.5.4/v2.5.5 results - using 
                       phylogenetically refined from the N0.tsv 
                       file)
    - orthofinder_og (OrthoFinder v2.5.4/v2.5.5 results - using 
                      coarse ortholog groups from the 
                      Orthogroups.tsv file)
	""", formatter_class=RawTextRichHelpFormatter)

	parser.add_argument('-i', '--results-dir', help='Resulting directory produced by orthology prection software.', required=True)
	parser.add_argument('-m', '--method', help='The name of the orthology prediction software - see help function for supported methods.', required=True)
	parser.add_argument('-t', '--total-proteins', type=int, help='Total number of proteins in the input file. This is used to calculate the single copy core gene fraction.', required=True)
	parser.add_argument('-o', '--output-file', help='Output file - default is standard output.', required=False, default=None)
	parser.add_argument('-mm', '--max_memory', type=int, help='Uses resource module to set soft memory limit. Provide in Giga-bytes.\nGenerally memory shouldn\'t be a major concern unless working\nwith hundreds of large metagenomes. [currently\nexperimental; default is None].', default=None, required=False)
	parser.add_argument('-v', '--version', action='store_true', help="Get version and exit.", required=False, default=False)

	args = parser.parse_args()
	return args

valid_software = set(['bofasa', 'sonicparanoid', 'pirate', 'panaroo', 'scarap', 'orthofinder_hog', 'orthofinder_og'])

def extract_og_pairs():
	"""
	Void function which runs primary workflow for program.
	"""

	# get version
	version = util.getVersion()

	if len(sys.argv)>1 and ('-v' in set(sys.argv) or '--version' in set(sys.argv)):
		sys.stdout.write(version + '\n')
		sys.exit(0)

	"""
	PARSE ARGUMENTS
	"""
	myargs = create_parser()

	input_dir = os.path.abspath(myargs.results_dir) + '/'
	outfile = myargs.output_file
	method = myargs.method
	max_memory = myargs.max_memory
	total_input_proteins = myargs.total_proteins

	"""
	START WORKFLOW
	"""

	# set max memory limit
	if max_memory != None:
		try:
			util.memory_limit(max_memory)
		except Exception as e:
			sys.stdout.write("Error setting memory limit\n")

	try:
		assert(method in valid_software)
	except:
		msg = 'Method %s not in set of accepted methods.' % method
		sys.stderr.write(msg)
		sys.exit(1)

	outf_handle = sys.stdout
	if outfile != None:
		outf_handle = open(outfile, 'w')


	if method == 'bofasa':
		result_file = input_dir + '/Final_Results/Protein_Ortholog_Groups.tsv'        
		try:
			assert(os.path.isfile(result_file))
		except:
			msg = 'Error: Issue validating the existence of file: %s' % result_file
			sys.stderr.write(msg)
			sys.exit(1)

		tot_samples = None
		proteins_in_ogs = 0
		with open(result_file) as orf:
			for i, line in enumerate(orf):
				if i == 0: continue
				line = line.rstrip('\n')
				ls = line.split('\t')
				og = ls[0]
				og_samples = 0
				tot_samples = 0
				sc_flag = True
				og_copy_counts = []
				for lts in ls[1:]:
					tot_samples += 1
					if lts.strip() != '':
						og_samples += 1
					if ',' in lts:
						sc_flag = False
						og_copy_counts.append(len(lts.split(',')))
					elif lts.strip() != '':
						og_copy_counts.append(1)
				tot_proteins = sum(og_copy_counts)
				proteins_in_ogs +=  tot_proteins
				median_proteins = statistics.median(og_copy_counts)
				scc_flag = False
				if sc_flag == True and og_samples/tot_samples == 1.0:
					scc_flag = True
				outf_handle.write(og + '\t' + str(tot_proteins) + '\t' + str(median_proteins) + '\t' +
					              str(og_samples) + '\t' + str(tot_samples) + '\t' + str(sc_flag) + '\t' +
								  str(scc_flag) + '\n')
		
		if proteins_in_ogs < total_input_proteins:
			diff = total_input_proteins - proteins_in_ogs
			for i in range(1, diff + 1):
				outf_handle.write('SOG_%d\t1\t1\t1\t%d\tTrue\tFalse\n' % (i, tot_samples))

	elif method == 'sonicparanoid':
		info_file = input_dir + 'last_run_info.txt'
		try:
			assert(os.path.isfile(info_file))
		except:
			msg = 'Error: Issue validating the existence of file: %s' % info_file
			sys.stderr.write(msg)
			sys.exit(1)
		
		result_file = None
		with open(info_file) as oif:
			for line in oif:
				line = line.rstrip('\n')
				ls = line.split('\t')
				if ls[0] == 'Directory with ortholog groups:':
					result_file = ls[1] + 'flat.ortholog_groups.tsv'

		try:
			assert(os.path.isfile(result_file))
		except:
			msg = 'Error: Issue validating the existence of file: %s' % result_file
			sys.stderr.write(msg)
			sys.exit(1)
		
		tot_samples = None
		proteins_in_ogs = 0
		with open(result_file) as orf:
			for i, line in enumerate(orf):
				if i == 0: continue
				line = line.rstrip('\n')
				ls = line.split('\t')
				og = ls[0]
				og_samples = 0
				tot_samples = 0
				sc_flag = True
				og_copy_counts = []
				for lts in ls[1:]:
					tot_samples += 1
					if lts.strip() != '*':
						og_samples += 1
					if ',' in lts:
						sc_flag = False
						og_copy_counts.append(len(lts.split(',')))
					elif lts.strip() != '*':
						og_copy_counts.append(1)
				tot_proteins = sum(og_copy_counts)
				proteins_in_ogs +=  tot_proteins
				median_proteins = statistics.median(og_copy_counts)
				scc_flag = False
				if sc_flag == True and og_samples/tot_samples == 1.0:
					scc_flag = True
				outf_handle.write(og + '\t' + str(tot_proteins) + '\t' + str(median_proteins) + '\t' +
					              str(og_samples) + '\t' + str(tot_samples) + '\t' + str(sc_flag) + '\t' +
								  str(scc_flag) + '\n')
		if proteins_in_ogs < total_input_proteins:
			diff = total_input_proteins - proteins_in_ogs
			for i in range(1, diff + 1):
				outf_handle.write('SOG_%d\t1\t1\t1\t%d\tTrue\tFalse\n' % (i, tot_samples))

	elif method == 'panaroo':
		result_file = input_dir + 'gene_presence_absence.csv'

		try:
			assert(os.path.isfile(result_file))
		except:
			msg = 'Error: Issue validating the existence of file: %s' % result_file
			sys.stderr.write(msg)
			sys.exit(1)
		 
		proteins_in_ogs = 0 
		tot_samples = None
		with open(result_file) as orf:
			for i, line in enumerate(orf):
				if i == 0: continue
				line = line.rstrip('\n')
				ls = line.split(',')
				og = ls[0]
				og_samples = 0
				tot_samples = 0
				sc_flag = True
				og_copy_counts = []
				for lts in ls[3:]:
					tot_samples += 1
					if lts.strip() != '':
						og_samples += 1
					if ',' in lts:
						sc_flag = False
						og_copy_counts.append(len(lts.split(';')))
					elif lts.strip() != '':
						og_copy_counts.append(1)
				tot_proteins = sum(og_copy_counts)
				proteins_in_ogs +=  tot_proteins
				median_proteins = statistics.median(og_copy_counts)
				scc_flag = False
				if sc_flag == True and og_samples/tot_samples == 1.0:
					scc_flag = True
				outf_handle.write(og + '\t' + str(tot_proteins) + '\t' + str(median_proteins) + '\t' +
					              str(og_samples) + '\t' + str(tot_samples) + '\t' + str(sc_flag) + '\t' +
								  str(scc_flag) + '\n')

		if proteins_in_ogs < total_input_proteins:
			diff = total_input_proteins - proteins_in_ogs
			for i in range(1, diff + 1):
				outf_handle.write('SOG_%d\t1\t1\t1\t%d\tTrue\tFalse\n' % (i, tot_samples))

	elif method == 'pirate':
		result_file = input_dir + 'PIRATE.gene_families.ordered.tsv'		
		try:
			assert(os.path.isfile(result_file))
		except:
			msg = 'File not found %s' % result_file
			sys.stderr.write(msg + '\n')
			sys.exit(1)

		tot_samples = None
		proteins_in_ogs = 0
		with open(result_file) as orf:
			for i, line in enumerate(orf):
				if i == 0: continue
				line = line.rstrip('\n')
				ls = line.split('\t')
				og = ls[0]
				og_samples = 0
				tot_samples = 0
				sc_flag = True
				og_copy_counts = []
				for lts in ls[22:]:
					tot_samples += 1
					if lts.strip() != '':
						og_samples += 1
					if ',' in lts or ':' in lts:
						sc_flag = False
						og_copy_counts.append(len(lts.replace('(', '').replace(')', '').replace(':', ';').split(';')))
					elif lts.strip() != '':
						og_copy_counts.append(1)
				tot_proteins = sum(og_copy_counts)
				median_proteins = statistics.median(og_copy_counts)
				scc_flag = False
				if sc_flag == True and og_samples/tot_samples == 1.0:
					scc_flag = True
				outf_handle.write(og + '\t' + str(tot_proteins) + '\t' + str(median_proteins) + '\t' +
					              str(og_samples) + '\t' + str(tot_samples) + '\t' + str(sc_flag) + '\t' +
								  str(scc_flag) + '\n')

		if proteins_in_ogs < total_input_proteins:
			diff = total_input_proteins - proteins_in_ogs
			for i in range(1, diff + 1):
				outf_handle.write('SOG_%d\t1\t1\t1\t%d\tTrue\tFalse\n' % (i, tot_samples))

	elif method == 'scarap':
		result_file = input_dir + 'pangenome.tsv'		
		try:
			assert(os.path.isfile(result_file))
		except:
			msg = 'File not found %s' % result_file
			sys.stderr.write(msg + '\n')
			sys.exit(1)

		samples = set([])
		og_sample_lts = defaultdict(lambda: defaultdict(set))
		with open(result_file) as orf:
			for i, line in enumerate(orf):
				line = line.rstrip('\n')
				lt, g, og = line.split('\t')
				og_sample_lts[og][g].add(lt)
				samples.add(g)
	
		tot_samples = len(samples)
		proteins_in_ogs = 0
		for og in og_sample_lts:
			og_samples = 0
			sc_flag = True
			og_copy_counts = []
			for s in og_sample_lts[og]:
				og_samples += 1
				samp_cc = len(og_sample_lts[og][s])
				og_copy_counts.append(samp_cc)
				if samp_cc > 1:
					sc_flag = False

			tot_proteins = sum(og_copy_counts)
			proteins_in_ogs	+=  tot_proteins
			median_proteins = statistics.median(og_copy_counts)
			scc_flag = False
			if sc_flag == True and og_samples/tot_samples == 1.0:
				scc_flag = True
			outf_handle.write(og + '\t' + str(tot_proteins) + '\t' + str(median_proteins) + '\t' +
					              str(og_samples) + '\t' + str(tot_samples) + '\t' + str(sc_flag) + '\t' +
								  str(scc_flag) + '\n')

		if proteins_in_ogs < total_input_proteins:
			diff = total_input_proteins - proteins_in_ogs
			for i in range(1, diff + 1):
				outf_handle.write('SOG_%d\t1\t1\t1\t%d\tTrue\tFalse\n' % (i, tot_samples))

	elif method == 'orthofinder_og':

		subdirs = []
		for sd in os.listdir(input_dir):
			subdirs.append(sd)

		try:
			assert(len(subdirs) == 1)
		except:
			msg = 'None or multiple results found within OrthoFinder directory!'
			sys.stderr.write(msg + '\n')
			sys.exit(1)

		result_file = input_dir + subdirs[0] + '/Orthogroups/Orthogroups.tsv'

		try:
			assert(os.path.isfile(result_file))
		except:
			msg = 'File not found %s' % result_file
			sys.stderr.write(msg + '\n')
			sys.exit(1)

		tot_samples = None
		proteins_in_ogs = 0
		with open(result_file) as orf:
			for i, line in enumerate(orf):
				if i == 0: continue
				line = line.rstrip('\n')
				ls = line.split('\t')
				og = ls[0]
				og_samples = 0
				tot_samples = 0
				sc_flag = True
				og_copy_counts = []
				for lts in ls[1:]:
					tot_samples += 1
					if lts.strip() != '':
						og_samples += 1
					if ',' in lts:
						sc_flag = False
						og_copy_counts.append(len(lts.split(',')))
					elif lts.strip() != '':
						og_copy_counts.append(1)
				tot_proteins = sum(og_copy_counts)
				proteins_in_ogs +=  tot_proteins
				median_proteins = statistics.median(og_copy_counts)
				scc_flag = False
				if sc_flag == True and og_samples/tot_samples == 1.0:
					scc_flag = True
				outf_handle.write(og + '\t' + str(tot_proteins) + '\t' + str(median_proteins) + '\t' +
					              str(og_samples) + '\t' + str(tot_samples) + '\t' + str(sc_flag) + '\t' +
								  str(scc_flag) + '\n')
		
		if proteins_in_ogs < total_input_proteins:
			diff = total_input_proteins - proteins_in_ogs
			for i in range(1, diff + 1):
				outf_handle.write('SOG_%d\t1\t1\t1\t%d\tTrue\tFalse\n' % (i, tot_samples))

	elif method == 'orthofinder_hog':
		
		subdirs = []
		for sd in os.listdir(input_dir):
			subdirs.append(sd)

		try:
			assert(len(subdirs) == 1)
		except:
			msg = 'None or multiple results found within OrthoFinder directory!'
			sys.stderr.write(msg + '\n')
			sys.exit(1)

		result_file = input_dir + subdirs[0] + '/Phylogenetic_Hierarchical_Orthogroups/N0.tsv'

		try:
			assert(os.path.isfile(result_file))
		except:
			msg = 'File not found %s' % result_file
			sys.stderr.write(msg + '\n')
			sys.exit(1)

		tot_samples = None
		proteins_in_ogs = 0
		with open(result_file) as orf:
			for i, line in enumerate(orf):
				if i == 0: continue
				line = line.rstrip('\n')
				ls = line.split('\t')
				og = ls[0]
				og_samples = 0
				tot_samples = 0
				sc_flag = True
				og_copy_counts = []
				for lts in ls[3:]:
					tot_samples += 1
					if lts.strip() != '':
						og_samples += 1
					if ',' in lts:
						sc_flag = False
						og_copy_counts.append(len(lts.split(',')))
					elif lts.strip() != '':
						og_copy_counts.append(1)
				tot_proteins = sum(og_copy_counts)
				proteins_in_ogs +=  tot_proteins
				median_proteins = statistics.median(og_copy_counts)
				scc_flag = False
				if sc_flag == True and og_samples/tot_samples == 1.0:
					scc_flag = True
				outf_handle.write(og + '\t' + str(tot_proteins) + '\t' + str(median_proteins) + '\t' +
					              str(og_samples) + '\t' + str(tot_samples) + '\t' + str(sc_flag) + '\t' +
								  str(scc_flag) + '\n')
		
		if proteins_in_ogs < total_input_proteins:
			diff = total_input_proteins - proteins_in_ogs
			for i in range(1, diff + 1):
				outf_handle.write('SOG_%d\t1\t1\t1\t%d\tTrue\tFalse\n' % (i, tot_samples))

	if outfile != None:
		outf_handle.close()

if __name__ == '__main__':
	extract_og_pairs()
