#!/workspace/local/rauf/bofasa/conda_env/bin/python3.11

### Program: extract_og_pairs
### Author: Rauf Salamzade
### Kalan Lab
### UW Madison & McMaster University

# BSD 3-Clause License
#
# Copyright (c) 2024, Rauf Salamzade
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import os
import sys
import argparse
from collections import defaultdict
from bofasa import util
from rich_argparse import RawTextRichHelpFormatter

def create_parser():
    """ Parse arguments """
    parser = argparse.ArgumentParser(description="""
    Program: extract_og_pairs
    Authors: Rauf Salamzade, Aamuktha Kottapalli, Lindsay R. Kalan 
    Affiliation: University of Wisconsin - Madsion, McMaster University                               
                                  
    extract_og_pairs: a simple script to list pairs of proteins in the 
    same ortholog group for method comparison. 

    Options for software supported include:
    ===================================================================
    - bofasa 
    - sonicparanoid
    - panaroo
    - scarap
    - pirate
    - orthofinder_hog (OrthoFinder v2.5.4/v2.5.5 results - using 
                       phylogenetically refined from the N0.tsv 
                       file)
    - orthofinder_og (OrthoFinder v2.5.4/v2.5.5 results - using 
                      coarse ortholog groups from the 
                      Orthogroups.tsv file)
    """, formatter_class=RawTextRichHelpFormatter)

    parser.add_argument('-i', '--results-dir', help='Resulting directory produced by orthology prection software.', required=True)
    parser.add_argument('-m', '--method', help='The name of the orthology prediction software - see help function for supported methods.', required=True)
    parser.add_argument('-o', '--output-file', help='Output file - default is standard output.', required=False, default=None)
    parser.add_argument('-pi', '--pirate-input-dir', help='Input directory with GFFs for PIRATE - needed because PIRATE renames genes.', required=False, default=None)
    parser.add_argument('-pgi', '--pirate-gff-identifier', help='The identifier for CDS feautres in GFFs in the input directory for PIRATE. [Default is "ID"]', required=False, default="ID")
    parser.add_argument('-mm', '--max_memory', type=int, help='Uses resource module to set soft memory limit. Provide in Giga-bytes.\nGenerally memory shouldn\'t be a major concern unless working\nwith hundreds of large metagenomes. [currently\nexperimental; default is None].', default=None, required=False)
    parser.add_argument('-s', '--select-proteins', help='Select proteins to report.', required=False, default=None)
    parser.add_argument('-is', '--include-singletons', help='Include singletons in the output.', required=False, default=False, action='store_true')
    parser.add_argument('-v', '--version', action='store_true', help="Get version and exit.", required=False, default=False)

    args = parser.parse_args()
    return args

valid_software = set(['bofasa', 'sonicparanoid', 'pirate', 'panaroo', 'scarap', 'orthofinder_hog', 'orthofinder_og'])

def extract_og_pairs():
    """
    Void function which runs primary workflow for program.
    """

    # get version
    version = util.getVersion()

    if len(sys.argv)>1 and ('-v' in set(sys.argv) or '--version' in set(sys.argv)):
        sys.stdout.write(version + '\n')
        sys.exit(0)

    """
    PARSE ARGUMENTS
    """
    myargs = create_parser()

    input_dir = os.path.abspath(myargs.results_dir) + '/'
    outfile = myargs.output_file
    method = myargs.method
    max_memory = myargs.max_memory
    pirate_input_dir = myargs.pirate_input_dir
    pirate_gff_identifier = myargs.pirate_gff_identifier
    select_proteins_file = myargs.select_proteins
    include_singletons = myargs.include_singletons

    """
    START WORKFLOW
    """

    # set max memory limit
    if max_memory != None:
        try:
            util.memory_limit(max_memory)
        except Exception as e:
            sys.stdout.write("Error setting memory limit\n")

    try:
        assert(method in valid_software)
    except:
        msg = 'Method %s not in set of accepted methods.' % method
        sys.stderr.write(msg)
        sys.exit(1)

    outf_handle = sys.stdout
    if outfile != None:
        outf_handle = open(outfile, 'w')

    outf_handle.write('DATASET_HEATMAP\n')
    outf_handle.write('SEPARATOR TAB\n')
    outf_handle.write('DATASET_LABEL\t' + str(method) + '\n')
    outf_handle.write('COLOR\t#000000\n')
    
    select_proteins = set([])
    if select_proteins_file != None:
        with open(select_proteins_file) as spf:
            for line in spf:
                line = line.rstrip('\n')
                if line.startswith('#'): continue
                ls = line.split()
                if len(ls) == 0: continue
                select_proteins.add(ls[0])

    if method == 'bofasa':
        result_file = input_dir + '/Final_Results/Protein_Ortholog_Groups.tsv'        
        try:
            assert(os.path.isfile(result_file))
        except:
            msg = 'Error: Issue validating the existence of file: %s' % result_file
            sys.stderr.write(msg)
            sys.exit(1)

        ogs = set([])
        prot_ogs = {}
        with open(result_file) as orf:
            for i, line in enumerate(orf):
                if i == 0: continue
                line = line.rstrip('\n')
                ls = line.split('\t')
                og = ls[0]
                og_lts = set([])
                for lts in ls[1:]:
                    for lt in lts.split(','):
                        if lt.strip() == '': continue
                        og_lts.add(lt.strip())
                og = ls[0]
                lt_list = []
                if select_proteins_file != None:
                    if len(og_lts.intersection(select_proteins)) == 0: continue
                    for lt in og_lts:
                        if lt in select_proteins:
                            lt_list.append(lt)
                            prot_ogs[lt] = og

                    if len(lt_list) >= 2 or include_singletons:
                        ogs.add(og)
                else:
                    for lt in og_lts:
                        lt_list.append(lt)
                        prot_ogs[lt] = og
                    if len(lt_list) >= 2 or include_singletons:
                        ogs.add(og)
        
        outf_handle.write('FIELD_LABELS\t' + '\t'.join(sorted(ogs)) + '\n')
        outf_handle.write('DATA\n')
        for lt in sorted(prot_ogs.keys()):
            lt_og = prot_ogs[lt]
            printlist = [lt]
            for og in sorted(ogs):
                if og == lt_og:
                    printlist.append('1')
                else:
                    printlist.append('0')
            outf_handle.write('\t'.join(printlist) + '\n')
            
    elif method == 'sonicparanoid':
        info_file = input_dir + 'last_run_info.txt'
        try:
            assert(os.path.isfile(info_file))
        except:
            msg = 'Error: Issue validating the existence of file: %s' % info_file
            sys.stderr.write(msg)
            sys.exit(1)
        
        result_file = None
        with open(info_file) as oif:
            for line in oif:
                line = line.rstrip('\n')
                ls = line.split('\t')
                if ls[0] == 'Directory with ortholog groups:':
                    result_file = ls[1] + 'flat.ortholog_groups.tsv'

        try:
            assert(os.path.isfile(result_file))
        except:
            msg = 'Error: Issue validating the existence of file: %s' % result_file
            sys.stderr.write(msg)
            sys.exit(1)
         
        ogs = set([])
        prot_ogs = {}
        with open(result_file) as orf:
            for i, line in enumerate(orf):
                if i == 0: continue
                line = line.rstrip('\n')
                ls = line.split('\t')
                og = ls[0]
                og_lts = set([])
                for lts in ls[1:]:
                    if lts == '*': continue
                    for lt in lts.split(','):
                        if lt.strip() == '': continue
                        og_lts.add(lt.strip())
                og = ls[0]
                lt_list = []
                if select_proteins_file != None:
                    if len(og_lts.intersection(select_proteins)) == 0: continue
                    for lt in og_lts:
                        if lt in select_proteins:
                            lt_list.append(lt)
                            prot_ogs[lt] = og

                    if len(lt_list) >= 2 or include_singletons:
                        ogs.add(og)
                else:
                    for lt in og_lts:
                        lt_list.append(lt)
                        prot_ogs[lt] = og
                    if len(lt_list) >= 2 or include_singletons:
                        ogs.add(og)
        
        outf_handle.write('FIELD_LABELS\t' + '\t'.join(sorted(ogs)) + '\n')
        outf_handle.write('DATA\n')
        for lt in sorted(prot_ogs.keys()):
            lt_og = prot_ogs[lt]
            printlist = [lt]
            for og in sorted(ogs):
                if og == lt_og:
                    printlist.append('1')
                else:
                    printlist.append('0')
            outf_handle.write('\t'.join(printlist) + '\n')

    elif method == 'panaroo':
        result_file = input_dir + 'gene_presence_absence.csv'

        try:
            assert(os.path.isfile(result_file))
        except:
            msg = 'Error: Issue validating the existence of file: %s' % result_file
            sys.stderr.write(msg)
            sys.exit(1)
         
        ogs = set([])
        prot_ogs = {}
        with open(result_file) as orf:
            for i, line in enumerate(orf):
                if i == 0: continue
                line = line.rstrip('\n')
                ls = line.split(',')
                og_lts = set([])
                for lts in ls[3:]:
                    for lt in lts.split(';'):
                        if lt.strip() == '': continue
                        og_lts.add(lt)
                og = ls[0]
                lt_list = []
                if select_proteins_file != None:
                    if len(og_lts.intersection(select_proteins)) == 0: continue
                    for lt in og_lts:
                        if lt in select_proteins:
                            lt_list.append(lt)
                            prot_ogs[lt] = og

                    if len(lt_list) >= 2 or include_singletons:
                        ogs.add(og)
                else:
                    for lt in og_lts:
                        lt_list.append(lt)
                        prot_ogs[lt] = og
                    if len(lt_list) >= 2 or include_singletons:
                        ogs.add(og)
        
        outf_handle.write('FIELD_LABELS\t' + '\t'.join(sorted(ogs)) + '\n')
        outf_handle.write('DATA\n')
        for lt in sorted(prot_ogs.keys()):
            lt_og = prot_ogs[lt]
            printlist = [lt]
            for og in sorted(ogs):
                if og == lt_og:
                    printlist.append('1')
                else:
                    printlist.append('0')
            outf_handle.write('\t'.join(printlist) + '\n')

    elif method == 'pirate':    
        try:
            assert(os.path.isdir(pirate_input_dir))
        except:
            msg = 'PIRATE input directory with GFFs was not found!'
            sys.stderr.write(msg + '\n')
            sys.exit(1)

        sample_ids_in_order = defaultdict(list)
        for f in os.listdir(pirate_input_dir):
            s = '_'.join(f.split('.')[:-1])
            with open(pirate_input_dir + f) as ogff:
                for line in ogff:
                    if line.startswith('#'): continue
                    line = line.strip()
                    ls = line.split('\t')
                    if len(ls) < 6: continue
                    if ls[2] != 'CDS': continue
                    gid = ls[-1].split(pirate_gff_identifier + '=')[1].split(';')[0]
                    sample_ids_in_order[s].append(gid)

        g2l_file = input_dir + 'genome2loci.tab'        
        try:
            assert(os.path.isfile(g2l_file))
        except:
            msg = 'File not found %s' % g2l_file
            sys.stderr.write(msg + '\n')
            sys.exit(1)

        gid_to_gname = {}
        with open(g2l_file) as og2f:
            for line in og2f:
                line = line.strip()
                ls = line.split()
                s = ls[1]
                gid = int(ls[0].split('_')[-1])-1
                gname = sample_ids_in_order[s][gid]
                gid_to_gname[ls[0]] = gname

        result_file = input_dir + 'PIRATE.gene_families.ordered.tsv'        
        try:
            assert(os.path.isfile(result_file))
        except:
            msg = 'File not found %s' % result_file
            sys.stderr.write(msg + '\n')
            sys.exit(1)

        ogs = set([])
        prot_ogs = {}
        with open(result_file) as orf:
            for i, line in enumerate(orf):
                if i == 0: continue
                line = line.rstrip('\n')
                ls = line.split('\t')
                og_lts = set([])
                for lts in ls[22:]:
                    for lt in lts.split(';'):
                        if lt.strip() == '': continue
                        if lt.startswith('('):
                            lt = lt[1:-1]
                            for slt in lt.split(':'):
                                og_lts.add(gid_to_gname[slt.strip()])
                        else:
                            og_lts.add(gid_to_gname[lt.strip()])
                og = ls[0]
                lt_list = []
                if select_proteins_file != None:
                    if len(og_lts.intersection(select_proteins)) == 0: continue
                    for lt in og_lts:
                        if lt in select_proteins:
                            lt_list.append(lt)
                            prot_ogs[lt] = og

                    if len(lt_list) >= 2 or include_singletons:
                        ogs.add(og)
                else:
                    for lt in og_lts:
                        lt_list.append(lt)
                        prot_ogs[lt] = og
                    if len(lt_list) >= 2 or include_singletons:
                        ogs.add(og)
        
        outf_handle.write('FIELD_LABELS\t' + '\t'.join(sorted(ogs)) + '\n')
        outf_handle.write('DATA\n')
        for lt in sorted(prot_ogs.keys()):
            lt_og = prot_ogs[lt]
            printlist = [lt]
            for og in sorted(ogs):
                if og == lt_og:
                    printlist.append('1')
                else:
                    printlist.append('0')
            outf_handle.write('\t'.join(printlist) + '\n')  
            
    elif method == 'scarap':
        result_file = input_dir + 'pangenome.tsv'       
        try:
            assert(os.path.isfile(result_file))
        except:
            msg = 'File not found %s' % result_file
            sys.stderr.write(msg + '\n')
            sys.exit(1)

        og_lts = defaultdict(set)
        with open(result_file) as orf:
            for i, line in enumerate(orf):
                line = line.rstrip('\n')
                lt, g, og = line.split('\t')
                og_lts[og].add(lt)
                
        ogs = set([])
        prot_ogs = {}
        for og in og_lts:
            lt_list = []
            if select_proteins_file != None:
                if len(og_lts[og].intersection(select_proteins)) == 0: continue
                for lt in og_lts[og]:
                    if lt in select_proteins:
                        lt_list.append(lt)
                        prot_ogs[lt] = og
                if len(lt_list) >= 2 or include_singletons:
                    ogs.add(og)
            else:
                for lt in og_lts[og]:
                    lt_list.append(lt)
                    prot_ogs[lt] = og
                if len(lt_list) >= 2 or include_singletons:
                    ogs.add(og)
        
        outf_handle.write('FIELD_LABELS\t' + '\t'.join(sorted(ogs)) + '\n')
        outf_handle.write('DATA\n')
        for lt in sorted(prot_ogs.keys()):
            lt_og = prot_ogs[lt]
            printlist = [lt]
            for og in sorted(ogs):
                if og == lt_og:
                    printlist.append('1')
                else:
                    printlist.append('0')
            outf_handle.write('\t'.join(printlist) + '\n')
        
    elif method == 'orthofinder_og':

        subdirs = []
        for sd in os.listdir(input_dir):
            subdirs.append(sd)

        try:
            assert(len(subdirs) == 1)
        except:
            msg = 'None or multiple results found within OrthoFinder directory!'
            sys.stderr.write(msg + '\n')
            sys.exit(1)

        result_file = input_dir + subdirs[0] + '/Orthogroups/Orthogroups.tsv'

        try:
            assert(os.path.isfile(result_file))
        except:
            msg = 'File not found %s' % result_file
            sys.stderr.write(msg + '\n')
            sys.exit(1)

        ogs = set([])
        prot_ogs = {}
        with open(result_file) as orf:
            for i, line in enumerate(orf):
                if i == 0: continue
                line = line.rstrip('\n')
                ls = line.split('\t')
                og_lts = set([])
                for lts in ls[1:]:
                    for lt in lts.split(','):
                        if lt.strip() == '': continue 
                        og_lts.add(lt.strip())
                og = ls[0]
                lt_list = []
                if select_proteins_file != None:
                    if len(og_lts.intersection(select_proteins)) == 0: continue
                    for lt in og_lts:
                        if lt in select_proteins:
                            lt_list.append(lt)
                            prot_ogs[lt] = og

                    if len(lt_list) >= 2 or include_singletons:
                        ogs.add(og)
                else:
                    for lt in og_lts:
                        lt_list.append(lt)
                        prot_ogs[lt] = og
                    if len(lt_list) >= 2 or include_singletons:
                        ogs.add(og)
        
        outf_handle.write('FIELD_LABELS\t' + '\t'.join(sorted(ogs)) + '\n')
        outf_handle.write('DATA\n')
        for lt in sorted(prot_ogs.keys()):
            lt_og = prot_ogs[lt]
            printlist = [lt]
            for og in sorted(ogs):
                if og == lt_og:
                    printlist.append('1')
                else:
                    printlist.append('0')
            outf_handle.write('\t'.join(printlist) + '\n')

    elif method == 'orthofinder_hog':
        
        subdirs = []
        for sd in os.listdir(input_dir):
            subdirs.append(sd)

        try:
            assert(len(subdirs) == 1)
        except:
            msg = 'None or multiple results found within OrthoFinder directory!'
            sys.stderr.write(msg + '\n')
            sys.exit(1)

        result_file = input_dir + subdirs[0] + '/Phylogenetic_Hierarchical_Orthogroups/N0.tsv'

        try:
            assert(os.path.isfile(result_file))
        except:
            msg = 'File not found %s' % result_file
            sys.stderr.write(msg + '\n')
            sys.exit(1)

        ogs = set([])
        prot_ogs = {}   
        with open(result_file) as orf:
            for i, line in enumerate(orf):
                if i == 0: continue
                line = line.rstrip('\n')
                ls = line.split('\t')
                og_lts = set([])
                for lts in ls[3:]:
                    for lt in lts.split(','):
                        if lt.strip() == '': continue 
                        og_lts.add(lt.strip())
                og = ls[0]
                lt_list = []
                if select_proteins_file != None:
                    if len(og_lts.intersection(select_proteins)) == 0: continue
                    for lt in og_lts:
                        if lt in select_proteins:
                            lt_list.append(lt)
                            prot_ogs[lt] = og

                    if len(lt_list) >= 2 or include_singletons:
                        ogs.add(og)
                else:
                    for lt in og_lts:
                        lt_list.append(lt)
                        prot_ogs[lt] = og
                    if len(lt_list) >= 2 or include_singletons:
                        ogs.add(og)
        
        outf_handle.write('FIELD_LABELS\t' + '\t'.join(sorted(ogs)) + '\n')
        outf_handle.write('DATA\n')
        for lt in sorted(prot_ogs.keys()):
            lt_og = prot_ogs[lt]
            printlist = [lt]
            for og in sorted(ogs):
                if og == lt_og:
                    printlist.append('1')
                else:
                    printlist.append('0')
            outf_handle.write('\t'.join(printlist) + '\n')

    if outfile != None:
        outf_handle.close()

if __name__ == '__main__':
    extract_og_pairs()

